### PR TITLE
P0ex01 fixes

### PR DESCRIPTION
**Pull request by qfeuilla**
' use instead of " for special characters.

some rephrasing

### CODE REVIEW

**Comment by AugustinLopez** [comment]
Few things to consider for keeping all exercises consistent:
- Shell command arrow: always `$>` ?
- Program with no argument when argument expected: either `do nothing / print error / print usage` ? Anything is acceptable as long as the program does not crash.

Nothing critical but since its the first module it might pay off to look extra professional.

**Comment by qfeuilla** [comment]
- for the shell command, yes always $>
- for the no argument i did either do nothing or print usage
- the print error is for wrong input (we will consider no argument is not a wrong input)

**Comment by AugustinLopez** [comment]
In that case we can apply the `$>` and maybe write `do nothing or print an usage` for the no argument case. We should have all case covered

**Review by ezalos — APPROVED** [review]
Changes are good for me

**Pull request closed without merging**
