### PR TITLE
P0ex00 fixes

### PR DESCRIPTION
**Pull request by AugustinLopez**
I feel like a bit more work can be achieved but it feels "okayish"

- Added explanation for the need of a environment manager

- Manual install on `/goinfre/$USER/miniconda3` path to prevent some issue with multiple conda installation on the same goinfre

- download manual for linux added (to be tested a bit more, especially the .bash_profile bit)

 - Installation now use `conda init`

- We now create a 42AI-$USER environment

- Added `pycodestyle` to the list of program downloaded

The automatic installation script seems to work but feel sluggish. I don't know if I have to blame the current state of 42 servers for that: they feel slow this december.

### Issue:
#125 
#126

### CODE REVIEW

**Comment by qfeuilla** [comment]
TODO:

**Comment by qfeuilla** [comment]
TODO:
- [ ] add conda to the getting started options to complete the questionnary
- [ ] add more question, like for example, remove one package at the creation of the env (like numpy) and ask the student to install it

**Comment by AugustinLopez** [comment]
Added more command + command with flags. Using `pycodestyle` when a lightweight package is preferable.

**Comment by qfeuilla** [comment]
i think the question are too 'specific', we must put simpler question, but that are really going to be useful to the student, for example, make them first uninstall and install numpy and after that make them save there env (so they see the real usage of requirments.txt), then destroy the env and finally recreat it from the save they did.

**Comment by AugustinLopez** [comment]
I simplified the questions.

After testing the installation of an `env` with the `requirements.txt`, IMO it is too complicated for an ex00.

`pip` and `conda` setup don't play nice together (from what I can read, problems started to arise with PEP 610). The best requirements.txt for conda user seems to be output by `conda list -e` which feels obscure for a beginner (will all internet answers promoting `pip freeze`).

**Pull request closed without merging**
