### PR TITLE
Add of "scikit-learn functions" as forbidden functions for K-Means

### PR DESCRIPTION
**Pull request by madvid**
Mention of scikit learn functions as forbidden function

### CODE REVIEW

**Review by tflahaul — APPROVED** [review]
bon pour moi

**Comment by qfeuilla** [comment]
i think we should say anything that do k-means automaticaly, it will be easier than to list every library that do k-means

**Review by qfeuilla — APPROVED** [review]
LGTM

**Review by qfeuilla — APPROVED** [review]
LGTM

**Pull request merged**
