### PR TITLE
Fix kwargs in day01/resources/banking_test*.py

### PR DESCRIPTION
**Pull request by Ibouch**
Fix issue #99

### CODE REVIEW

**Comment by Talasta** [comment]
I would prefer to merge into dev.

**Comment by Talasta** [comment]
Changed branch `master -> dev`

**Comment by matboivin** [comment]
Thanks @lbouch ! :tada:

**Comment by Ibouch** [comment]
> Thanks @lbouch ! 🎉

With pleasure 👍

**Pull request merged**
